//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author_Book
    {
        public int ID_Author { get; set; }
        public int ID_Book { get; set; }
        public Nullable<int> Publishing_day { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
