//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int ID_Bookmark { get; set; }
        public int Page { get; set; }
        public int ID_Book { get; set; }
        public int ID_Library_user { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Library_user Library_user { get; set; }
    }
}
